# Generated by Django 4.0 on 2023-06-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('enlace', models.URLField()),
                ('tipo', models.CharField(max_length=50)),
                ('gobernacion_maritima', models.CharField(max_length=50)),
                ('lugar', models.CharField(max_length=100)),
                ('ds', models.CharField(max_length=10)),
                ('tramite', models.CharField(max_length=50)),
                ('concesionario', models.CharField(max_length=100)),
                ('vigencia', models.CharField(max_length=50)),
            ],
        ),
    ]
