# Generated by Django 4.0 on 2023-06-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concesionesmaritimas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concesion',
            name='ds',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='concesion',
            name='gobernacion_maritima',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='concesion',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='concesion',
            name='tramite',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='concesion',
            name='vigencia',
            field=models.CharField(max_length=100),
        ),
    ]
